version: '3'
services:
  db:
    image: postgres:10.4
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment: 
      - POSTGRES_PASSWORD=postgres

  service:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  pg-data: